#!/bin/bash

set -e

error() {
  local message="${*}"
  echo "[ERROR] ${message}" >&2
  exit 1
}

for link in "${@}"; do
  if [[ ! -L $link ]]; then
    error "${link} is not a symlink"
  fi
done

for link in "${@}"; do
  target=$(readlink -f "${link}")
  rm -r "${link}" && cp -r "${target}" "${link}"
done
