#!/bin/bash

set -e

tmpfile="/tmp/maim.png"
screenshot_folder="$HOME/screenshots"

function usage {
    echo "Usage:"
    echo "$(basename $BASH_SOURCE) -{f,c}"
}

function screenshot_to_file {
    maim -sun 1 "${tmpfile}" && to_file
}

function screenshot_to_clipboard {
    maim -sun 1 | to_clipboard
}

function to_file {
    local date=$(date '+%F-%H%M%S')
    local size=$(identify -format '%wx%h' "${tmpfile}")
    local newname="${date}_${size}.png"
    mkdir -p "${screenshot_folder}"
    mv "${tmpfile}" "${screenshot_folder}/${newname}"
}

function to_clipboard {
    xclip -selection clipboard -t image/png "$@"
}

while getopts "fc" opt; do
    case "${opt}" in
    f)
        WHERE='file'
        ;;
    c)
        WHERE='clipboard'
        ;;
    esac
done

if [ -z "${WHERE+x}" ]; then
    usage
    exit 1
fi

functionname="screenshot_to_${WHERE}"
eval "${functionname}"
